### PR TITLE
enable kobuki Windows build

### PR DESCRIPTION
**Pull request by kejxu**
this library needs to be updated in order to enable the kobuki code base to build on Windows
- `-std=` is not supported on MSVC, use the compiler-agnostic `CMAKE_CXX_STANDARD` flag instead

this port points to the melodic release branch because it currently only targets ROS1.melodic

### CODE REVIEW

**Comment by stonier** [comment]
@kejxu I've got some time to start pushing on this now.

Any way you could build msvc into the actual checks rather than assuming it's available and setting it? i.e. here:

https://github.com/stonier/ecl_tools/blob/9d70b3ec322735dbe177aff2d5023fe80aee60ae/ecl_build/cmake/ecl_cx11.cmake#L1-L9

Is there a flag you can verify works with MSVC via `CHECK_CXX_COMPILER_FLAG`?

**Comment by stonier** [comment]
I've bumped the logic for requiring and enabling (in a cross platform way) cxx14 on the `devel` branch in #9 and cx11 in #10. I can backport that logic to melodic, however, did you actually use it anyhwhere? I don't see it being used in https://github.com/stonier/ecl_lite/pull/27 or https://github.com/stonier/ecl_core/pull/87.

**Comment by kejxu** [comment]
> I've bumped the logic for requiring and enabling (in a cross platform way) cxx14 on the `devel` branch in #9 and cx11 in #10. I can backport that logic to melodic

Sounds great!

> however, did you actually use it anyhwhere? I don't see it being used in [stonier/ecl_lite#27](https://github.com/stonier/ecl_lite/pull/27) or [stonier/ecl_core#87](https://github.com/stonier/ecl_core/pull/87).

I think these macros are already being used in [ecl_core](https://github.com/stonier/ecl_core/blob/devel/ecl_threads/CMakeLists.txt) (and there should be more instances like this). Since the original logic (`ecl_check_for_cxx11_compiler`) hard codes the `-std=` flag, this change was made to enable compiling with MSVC

**Comment by kejxu** [comment]
for the other question, MSVC uses [`/std:c++` flags](https://devblogs.microsoft.com/cppblog/standards-version-switches-in-the-compiler/), but as you mentioned, anything cross-platform might be the desirable solution so that we could let CMake do the dirty work.

**Comment by stonier** [comment]
Aha, I found the few references in the melodic branch enabling cxx11. 

```
./ecl_geometry/CMakeLists.txt:49:ecl_enable_cxx11_compiler()
./ecl_core_apps/CMakeLists.txt:38:ecl_enable_cxx11_compiler()
./ecl_statistics/CMakeLists.txt:41:ecl_enable_cxx11_compiler()
./ecl_linear_algebra/CMakeLists.txt:48:ecl_enable_cxx11_compiler()
./ecl_time/CMakeLists.txt:40:ecl_enable_cxx11_compiler()
./ecl_devices/CMakeLists.txt:39:ecl_enable_cxx11_compiler()
```

I'll backport the new cross platform api and see how it handles it.

**Comment by stonier** [comment]
Cross platform approach in 45edeb93. Released and tagged as `v0.61.8` for melodic.

Closing this PR in favour of that, if you have any issues with this, please open a new issue.

Moving on to dealing with the other ecl repositories.

**Comment by kejxu** [comment]
> Cross platform approach in [45edeb9](https://github.com/stonier/ecl_tools/commit/45edeb9313a951f37f2b68db10a9997c8c8e4f5d). Released and tagged as `v0.61.8` for melodic.

Thanks for back-porting the change! Will test this one out. Also thanks for educating me about `CMAKE_CXX_EXTENSIONS` and `CMAKE_CXX_STANDARD_REQUIRED`, will check CMake documentation on these 2.

**Pull request closed without merging**
