### PR TITLE
allow pedantic compilation

### PR DESCRIPTION
**Pull request by Karsten1987**
connects to https://github.com/stonier/ecl_core/pull/86#issuecomment-520537614

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

**Comment by stonier** [comment]
The `-Wall, -Wextra` are worth chasing. 

I wouldn't normally have set `-Wl,--no-as-needed` though. What is the reasoning behind that?

**Comment by Karsten1987** [comment]
> I wouldn't normally have set -Wl,--no-as-needed though. What is the reasoning behind that?

That linker option is already set in the current [upstream code](https://github.com/stonier/ecl_tools/pull/8/files#diff-938d69d8eaf19977a60abdff987c97d6L30). I don't know why this was set in the first place.

Given that this is a GNU linker option only (I believe according to [this](http://www.bnikolic.co.uk/blog/gnu-ld-as-needed.html)) I only set that option when being used on UNIX and not on OSX.

**Comment by stonier** [comment]
Oh indeed...That's interesting, I didn't even think to check for its absence in the left hand side of the diff. 

According to the comment, might have been something interesting going on with ros2 in it's early days. I'll dig...

**Comment by stonier** [comment]
Tests are all passing, dropped `-Wl, -no-as-needed` and also bumped the logic for cxx14 and warning checks in ecl over in #9 (now forcing `-Werror` and `-Wpedantic` for ecl everywhere.

Subsequently, dropping this in favour of that PR.

@Karsten1987 thanks for pushing on me to do this overhaul!

**Pull request closed without merging**
